services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=
  api:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports: 3000:3000
    depends_on:
      - api
